-- sys_menu data
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (1, 0, 'department', '部门管理', 1, 'tree', NULL);
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (2, 1, 'departmentQuery', '查询', 1, 'tree', '/department/query');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (3, 1, 'departmentReview', '待复核', 2, 'tree', '/department/review');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (4, 1, 'departmentReviewed', '已复核', 3, 'tree', '/department/reviewed');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (5, 0, 'post', '岗位管理', 2, 'tree', NULL);
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (6, 5, 'postQuery', '查询', 1, 'tree', '/post/query');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (7, 5, 'postReview', '待复核', 2, 'tree', '/post/review');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (8, 5, 'postReviewed', '已复核', 3, 'tree', '/post/reviewed');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (9, 0, 'userAdmin', '用户管理员管理', 3, 'tree', NULL);
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (10, 9, 'userAdminQuery', '查询', 1, 'tree', '/userAdmin/query');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (11, 9, 'userAdminReview', '待复核', 2, 'tree', '/userAdmin/review');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (12, 9, 'userAdminReviewed', '已复核', 3, 'tree', '/userAdmin/reviewed');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (13, 0, 'userOperate', '用户操作员管理', 4, 'tree', NULL);
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (14, 13, 'userOperateQuery', '查询', 1, 'tree', '/userOperate/query');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (15, 13, 'userOperateReview', '待复核', 2, 'tree', '/userOperate/review');
INSERT INTO sys_menu (id, pid, menu_code, menu_name, menu_order, icon, url) VALUES (16, 13, 'userOperateReviewed', '已复核', 3, 'tree', '/userOperate/reviewed');

-- sys_button data
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (1, 2, 'departmentQuery:query', '查询', 'POST', '/department/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (2, 2, 'departmentQuery:add', '新增', 'POST', '/department/add');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (3, 2, 'departmentQuery:update', '修改', 'POST', '/department/update');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (4, 2, 'departmentQuery:detail', '详情', 'POST', '/department/detail');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (5, 2, 'departmentQuery:export', '下载', 'POST', '/department/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (6, 2, 'departmentQuery:logout', '注销', 'POST', '/department/logout');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (7, 2, 'departmentQuery:userQuery', '用户查询', 'POST', '/department/userQuery');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (8, 3, 'departmentReview:query', '查询', 'POST', '/department/review/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (9, 3, 'departmentReview:review', '复核', 'POST', '/department/review/review');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (10, 3, 'departmentReview:export', '下载', 'POST', '/department/review/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (11, 4, 'departmentReviewed:query', '查询', 'POST', '/department/reviewed/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (12, 4, 'departmentReviewed:export', '下载', 'POST', '/department/reviewed/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (13, 6, 'postQuery:query', '查询', 'POST', '/post/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (14, 6, 'postQuery:add', '新增', 'POST', '/post/add');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (15, 6, 'postQuery:update', '修改', 'POST', '/post/update');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (16, 6, 'postQuery:detail', '详情', 'POST', '/post/detail');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (17, 6, 'postQuery:export', '下载', 'POST', '/post/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (18, 6, 'postQuery:logout', '注销', 'POST', '/post/logout');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (19, 6, 'postQuery:userQuery', '用户查询', 'POST', '/post/userQuery');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (20, 7, 'postReview:query', '查询', 'POST', '/post/review/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (21, 7, 'postReview:review', '复核', 'POST', '/post/review/review');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (22, 7, 'postReview:export', '下载', 'POST', '/post/review/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (23, 8, 'postReviewed:query', '查询', 'POST', '/post/reviewed/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (24, 8, 'postReviewed:export', '下载', 'POST', '/post/reviewed/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (25, 10, 'userAdminQuery:query', '查询', 'POST', '/userAdmin/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (26, 10, 'userAdminQuery:add', '新增', 'POST', '/userAdmin/add');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (27, 10, 'userAdminQuery:update', '修改', 'POST', '/userAdmin/update');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (28, 10, 'userAdminQuery:detail', '详情', 'POST', '/userAdmin/detail');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (29, 10, 'userAdminQuery:export', '下载', 'POST', '/userAdmin/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (30, 10, 'userAdminQuery:logout', '注销', 'POST', '/userAdmin/logout');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (31, 10, 'userAdminQuery:freeze', '冻结', 'POST', '/userAdmin/freeze');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (32, 10, 'userAdminQuery:unfreeze', '解冻', 'POST', '/userAdmin/unfreeze');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (33, 10, 'userAdminQuery:pwdReset', '密码重置', 'POST', '/userAdmin/pwdReset');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (34, 10, 'userAdminQuery:bindCert', '绑定证书', 'POST', '/userAdmin/bindCert');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (35, 11, 'userAdminReview:query', '查询', 'POST', '/userAdmin/review/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (36, 11, 'userAdminReview:review', '复核', 'POST', '/userAdmin/review/review');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (37, 11, 'userAdminReview:export', '下载', 'POST', '/userAdmin/review/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (38, 12, 'userAdminReviewed:query', '查询', 'POST', '/userAdmin/reviewed/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (39, 12, 'userAdminReviewed:export', '下载', 'POST', '/userAdmin/reviewed/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (40, 14, 'userOperateQuery:query', '查询', 'POST', '/userOperate/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (41, 14, 'userOperateQuery:add', '新增', 'POST', '/userOperate/add');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (42, 14, 'userOperateQuery:update', '修改', 'POST', '/userOperate/update');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (43, 14, 'userOperateQuery:detail', '详情', 'POST', '/userOperate/detail');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (44, 14, 'userOperateQuery:export', '下载', 'POST', '/userOperate/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (45, 14, 'userOperateQuery:logout', '注销', 'POST', '/userOperate/logout');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (46, 14, 'userOperateQuery:freeze', '冻结', 'POST', '/userOperate/freeze');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (47, 14, 'userOperateQuery:unfreeze', '解冻', 'POST', '/userOperate/unfreeze');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (48, 14, 'userOperateQuery:pwdReset', '密码重置', 'POST', '/userOperate/pwdReset');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (49, 14, 'userOperateQuery:bindCert', '绑定证书', 'POST', '/userOperate/bindCert');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (50, 14, 'userOperateQuery:assignPermission', '分配权限', 'POST', '/userOperate/assignPermission');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (51, 15, 'userOperateReview:query', '查询', 'POST', '/userOperate/review/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (52, 15, 'userOperateReview:review', '复核', 'POST', '/userOperate/review/review');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (53, 15, 'userOperateReview:export', '下载', 'POST', '/userOperate/review/export');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (54, 16, 'userOperateReviewed:query', '查询', 'POST', '/userOperate/reviewed/query');
INSERT INTO sys_button (id, menu_id, btn_code, btn_name, method, uri) VALUES (55, 16, 'userOperateReviewed:export', '下载', 'POST', '/userOperate/reviewed/export');
